[package]
name = "mtf"
version = "0.3.2"
edition = "2024"
description = "Markdown Table Formatter"
license = "MIT"
repository = "https://github.com/qtfkwk/mtf"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive", "wrap_help"] }
clap-cargo = "0.17.0"
gstring = "0.12.0"
pulldown-cmark = "0.13.0"
